### ISSUE TITLE
Сообщения из майнкрафта не отображаются в тг чате

### ISSUE THREAD

**Issue by Sh1zome** [vanutp/tgbridge#74]
### Describe the bug

настроил префикс ! для отправки сообщений из майнкрафта в чат тг, но они не отправляются в тг

![Image](https://github.com/user-attachments/assets/bae5f5eb-7dbc-4029-a49c-147206490354)

![Image](https://github.com/user-attachments/assets/447a043b-76aa-424c-b9cf-e4e4db82c1ec)

### Additional info

это локальный сервер, никаких плагинов на чат нет, настройки:

![Image](https://github.com/user-attachments/assets/83274f6b-cdcb-45d4-b027-b3e4850edaf1)

### Minecraft version

1.20.1

### Loader

(Neo)Forge

### tgbridge version

- [x] I'm running the latest version of the mod

**Comment by vanutp** [comment]
Не могу воспроизвести. Стоят ли еще какие-то моды? Можно полный лог?

**Comment by rainbowx666** [comment]
Аналогичная ошибка. Плагин 0.7.1, ядро purpur 1.21.4. Плагин на чат - ChatControl. На 1.21.1 и предыдущей версии плагина все работало исправно.

Конфиг:
```
# It's enough to set botToken and chatId for the plugin to work.
# When your group has topics enabled, you should also set topicId.
# See https://tgbridge.vanutp.dev for more information.
general:
  botToken: ""
  chatId: 
  topicId: 
messages:
  # ::: warning
  # Don't enable this if you have a chat plugin installed.
  # See [Compatibility](https://tgbridge.vanutp.dev/en/compatibility#chat) for more info
  # :::
  # If this value is set, messages without specified prefix won't be forwarded to Telegram.
  # Example: "!" (quotes are required)
  # Default value: null (disabled)
  requirePrefixInMinecraft: null
  # Set to `true` to keep the prefix specified in the above setting in the message
  keepPrefix: false
  # Chat messages sent within the specified interval will be merged in one.
  # The value is specified in seconds
  # Default value: 0 (disabled)
  mergeWindow: 0
  # Set to `true` to use real player username instead of display name in all Telegram messages
  useRealUsername: false
integrations:
  # If this value is set, waypoints shared from Xaero's Minimap/World Map will be rendered
  # as links to a specified BlueMap instance.
  # Example: https://map.example.com
  # Default value: null (disabled)
  bluemapUrl: null
  # The chat name to forward messages from.
  # Only has an effect when a compatible chat plugin with support for named chats, such as Chatty, is installed.
  # (see [Compatibility](https://tgbridge.vanutp.dev/en/compatibility#chat))
  globalChatName: "global"
  # See also: [Compatibility](https://tgbridge.vanutp.dev/en/compatibility#chat)
  # Use this if you have an incompatible plugin, such as CMI or AdvancedChat installed.
  # Will register a legacy chat listener with LOWEST priority
  # and only forward messages that start with the specified string.
  # Currently this only has an effect on Paper.
  # Example: "!" (quotes are required)
  # Default value: null (disabled)
  incompatiblePluginChatPrefix: "!"
events:
  advancementMessages:
    enable: true
    # Configure forwarding of each advancement type
    enableTask: true
    # Configure forwarding of each advancement type
    enableGoal: true
    # Configure forwarding of each advancement type
    enableChallenge: true
    # Include advancement descriptions in Telegram messages
    showDescription: true
  enableDeathMessages: true
  enableJoinMessages: true
  enableLeaveMessages: true
  # If a player leaves and then joins within the specified time interval,
  # the leave and join messages will be deleted.
  # This is useful when players frequently re-join, for example because of connection problems.
  # Only has effect when both enableJoinMessages and enableLeaveMessages are set to true.
  # The value is specified in seconds
  # Default value: 0 (disabled)
  leaveJoinMergeWindow: 0
  # Whether to send a Telegram message when the server starts
  enableStartMessages: true
  # Whether to send a Telegram message when the server stops
  enableStopMessages: true
advanced:
  botApiUrl: "https://api.telegram.org"
# Config file version. Don't change manually
version: 3
```

В логе дефолтные сообщения о запуске плагина, ошибок не наблюдается.
